name: cat_concierge
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.2.0
  animated_size_and_fade: ^3.0.1
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.1
  azlistview: ^2.0.0
  boxy: ^2.0.8
  built_collection: ^5.1.1
  cached_network_image: ^3.2.3
  camerawesome: ^1.4.0
  carousel_slider: ^4.2.1
  connectivity_plus: ^3.0.3
  country_codes: ^2.2.0
  cupertino_icons: ^1.0.5
  device_info_plus: ^8.1.0
  diacritic: ^0.1.3
  dio: ^5.0.3
  dotted_border: ^2.0.0+3
  dotted_line: ^3.1.0
  dynamic_color: ^1.6.2
  easy_localization: ^3.0.1
  encrypt: ^5.0.1
  equatable: ^2.0.5
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.5
  flutter_keyboard_visibility: ^5.4.0
  flutter_multi_formatter: ^2.10.2
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.4
  focus_detector: ^2.0.1
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  google_fonts: ^4.0.3
  google_mlkit_barcode_scanning: ^0.6.0
  google_mlkit_commons: ^0.3.0
  google_mlkit_text_recognition: ^0.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  logging: ^1.1.1
  material_color_utilities: ^0.2.0
  modal_bottom_sheet: 3.0.0-pre
  one:
    git:
      url: https://github.com/hieutv-dng/one.dart.git
      ref: fbfa1ee
  one_checkbox:
    git:
      url: https://github.com/hieutv-dng/one_checkbox.git
  open_filex: ^4.3.2
  package_info_plus: ^3.0.3
  path: ^1.8.2
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  pull_to_refresh: ^2.0.0
  retrofit: ^4.0.1
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  smart_auth: ^1.0.8
  timeago: ^3.3.0
  tuple: ^2.0.1
  camera: ^0.10.4

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1

flutter_icons:
  ios: true
  image_path_ios: "assets/logo/ic_launcher.png"
  remove_alpha_ios: true
  android: true
  image_path_android: "assets/logo/ic_launcher.png"
  adaptive_icon_background: "#275FC4"
  adaptive_icon_foreground: "assets/logo/ic_launcher_adaptive_fore.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/localization/
    - assets/logo/
    - assets/svgs/
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
